servidor.puerto=6000
db.url=jdbc:sqlserver://localhost:1433;databaseName=Telefonia;encrypt=true;trustServerCertificate=true
db.user=telefonia_user
db.password=Telefonia2025!
bitacora.archivo=bitacora_proveedor.txt
